import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "../_components/Navbar";
import { Footer } from "../_components/Footer";

import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

const jakarta = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Workio",
  description: "Generated by Strapi + Next.js 14.1 - using GraphQL",
};

const RootLayout = async ({
  children,
  params: { lang },
}: Readonly<{
  children: React.ReactNode;
  params: { [lang: string]: "en" | "cs" };
}>) => {
  return (
    <html lang="en" className={jakarta.className}>
      <body className="bg-white w-full flex flex-col justify-between overflow-x-hidden min-h-screen">
        <Navbar locale={lang} />
        {children}
        <Footer locale={lang} />
        <ToastContainer />
      </body>
    </html>
  );
};

export default RootLayout;
