import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "../_components/Navbar";
import { Footer } from "../_components/Footer";
import { ContactForm } from "../_components/ContactForm";

const jakarta = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Workio Webpage",
  description: "Generated by Strapi + Next.js 14.1 - using GraphQL",
};

const RootLayout = async ({
  children,
  params: { lang },
}: Readonly<{
  children: React.ReactNode;
  params: { [lang: string]: "en" | "cs" };
}>) => {
  return (
    <html lang="en" className={jakarta.className}>
      <body className="bg-white w-screen overflow-x-hidden">
        <div className="">
          <Navbar locale={lang} />
          {children}
          <ContactForm locale={lang} />
          <Footer locale={lang} />
        </div>
      </body>
    </html>
  );
};

export default RootLayout;
